Sub Init()

    print "BasicPersonNode:Init"

    m.top.observeFieldScoped("data", "OnDataChanged")

End Sub


Sub OnDataChanged(event as object)

    print "BasicPersonNode:OnDataChanged"

    data = event.getData()
    if data = invalid then return

    m.top.id = data.tmdbId.toStr()
    m.top.title = data.Name
    m.top.sdGridPosterUrl = data.AvatarUrl
    m.top.hdGridPosterUrl = data.AvatarUrl
    m.top.fhdGridPosterUrl = data.AvatarUrl
    m.top.creditRole = data.role

End Sub